services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
        - "8080:8080"
        volumes:
          - .:/workspace/app
        environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/NetflixJava
          SPRING_DATASOURCE_USERNAME: test
          SPRING_DATASOURCE_PASSWORD: test
          SPRING_JPA_HIBERNATE_DDL_AUTO: update
        depends_on:
        - db
    db:
      image: postgres:latest
      environment:
        POSTGRES_DB: NetflixJava
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
      volumes:
        - postgres-data:/var/lib/postgresql/data
    frontend:
      build:
        context: "./Frontend"
        dockerfile: "./Dockerfile"
      ports:
        - "5173:5173"
      volumes:
        - ./Frontend:/app
        - /app/node_modules
      environment:
        - VITE_PORT=5173
        - VITE_HOST=0.0.0.0
      depends_on:
        - api
    proxy:
      image: nginx
      volumes:
        - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./Nginx/localhost.crt:/etc/nginx/localhost.crt
        - ./Nginx/localhost.key:/etc/nginx/localhost.key
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - frontend
        - api
    minio:
      image: quay.io/minio/minio
      command: server --console-address ":9001" /data
      volumes:
        - '~/minio/data:/data'
      ports:
        - "9000:9000"
        - "9001:9001"
      environment:
        MINIO_ROOT_PASSWORD: minioadmin
        MINIO_ROOT_USER: minioadmin
volumes:
    postgres-data: