server:
  port: 8080

jwt:
  secret:
    access: and0LnNlY3JldC5hY2Nlc3Muand0LnNlY3JldC5hY2Nlc3M=
    refresh: and0LnNlY3JldC5yZWZyZXNoLmp3dC5zZWNyZXQucmVmcmVzaA==

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/NetflixJava}
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "AlexeiStukov1999@gmail.com"
    password: "dmecmtrtyrndfvza"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
    protocol: smtp

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db-changelog.xml
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/NetflixJava}
    user: test
    password: test
    driver-class-name: org.postgresql.Driver


  freemarker:
    template-loader-path: /WEB-INF/templates/
    suffix: .ftl

mail:
  content: "Dear {name}, please follow the link below for verify your account: <a href={url}>VERIFY<a/>"
  from: "AlexeiStukov1999@gmail.com"
  sender: Test Application
  subject: Please verify your account